apiVersion: v1
kind: Service
metadata:
  name: ms-clientes
  namespace: dan
  labels:
    app: ms-clientes
spec:
  selector:
    app: ms-clientes
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
