apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: dan
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 62.6.0
    chart: kube-prometheus-stack-62.6.0
    heritage: Helm
    release: dan
  name: ms-clientes-sm
  namespace: monitoring
spec:
  endpoints:
  - path: /actuator/prometheus
    port: http
    interval: 15s
  namespaceSelector:
    matchNames:
    - dan
  selector:
    matchLabels:
      app: ms-clientes