fullnameOverride: kube-prometheus
namespaceOverride: monitoring
alertmanager:
  enabled: false
prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
prometheus:
  prometheusSpec:
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    retention: 1d
