auth:
  rootPassword: "danrootpassword"
  createDatabase: true
  database: "dandb"
  username: "danuser"
  password: "danpassword"
primary:
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi